services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: relai-gateway-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: ./relai-gateway
    depends_on:
      - dummy-backend
    environment:
      - USE_DUMMY_BACKEND=${USE_DUMMY_BACKEND}

  dummy-backend:
    build:
      context: loadtest
      dockerfile: Dockerfile
    container_name: dummy-backend
    environment:
      - DUMMY_BACKEND=1
      - USE_DUMMY_BACKEND=${USE_DUMMY_BACKEND}
    entrypoint: ["sh", "-c", "if [ \"$USE_DUMMY_BACKEND\" = \"1\" ]; then ./dummy-backend; else sleep infinity; fi"]